### PR TITLE
Fix the torchtolinalg == False passpipeline

### PR DESCRIPTION
**Pull request by AmosLewis**
There tests all based on the torch-mlir&iree llvm b3291793f119 Apr 30 and iree a075013cf May 7th.

`python ./run.py --torchmlirbuild ../../torch-mlir/build --tolerance 0.001 0.001 --cachedir ./huggingface_cache --ireebuild ../../iree-build  -f pytorch -g models --mode onnx --report`
Status report for run: test-run using mode:onnx todtype:default backend:llvm-cpu

| tests                                            | model-run   | onnx-import   | torch-mlir   | iree-compile   | inference   |
|:-------------------------------------------------|:------------|:--------------|:-------------|:---------------|:------------|
| pytorch/models/gpt2                              | passed      | passed        | passed       | passed         | passed      |
| pytorch/models/opt-125M                          | passed      | passed        | passed       | failed         | notrun      |
| pytorch/models/bart-large                        | passed      | passed        | passed       | failed         | notrun      |
| pytorch/models/whisper-base                      | passed      | passed        | passed       | passed         | passed      |
| pytorch/models/beit-base-patch16-224-pt22k-ft22k | passed      | passed        | passed       | passed         | passed      |
| pytorch/models/deit-small-distilled-patch16-224  | passed      | passed        | passed       | failed         | notrun      |
| pytorch/models/resnet50                          | passed      | passed        | passed       | passed         | passed      |
| pytorch/models/llama2-7b-GPTQ                    | failed      | notrun        | notrun       | notrun         | notrun      |
| pytorch/models/mobilebert-uncased                | passed      | passed        | passed       | passed         | passed      |
| pytorch/models/vicuna-13b-v1.3                   | failed      | notrun        | notrun       | notrun         | notrun      |
| pytorch/models/phi-1_5                           | passed      | passed        | passed       | passed         | mismatch    |
| pytorch/models/opt-350m                          | passed      | passed        | passed       | failed         | notrun      |
| pytorch/models/vit-base-patch16-224              | passed      | passed        | passed       | failed         | notrun      |
| pytorch/models/phi-2                             | passed      | passed        | passed       | passed         | mismatch    |
| pytorch/models/dlrm                              | passed      | passed        | failed       | notrun         | notrun      |
| pytorch/models/gpt2-xl                           | passed      | passed        | passed       | passed         | passed      |
| pytorch/models/opt-125m-gptq                     | failed      | notrun        | notrun       | notrun         | notrun      |
| pytorch/models/whisper-medium                    | passed      | passed        | passed       | passed         | passed      |
| pytorch/models/stablelm-3b-4e1t                  | passed      | failed        | notrun       | notrun         | notrun      |
| pytorch/models/opt-1.3b                          | passed      | passed        | passed       | failed         | notrun      |
| pytorch/models/whisper-small                     | passed      | passed        | passed       | passed         | passed      |
| pytorch/models/t5-large                          | passed      | passed        | passed       | passed         | passed      |
| pytorch/models/gemma-7b                          | failed      | notrun        | notrun       | notrun         | notrun      |
| pytorch/models/miniLM-L12-H384-uncased           | passed      | passed        | passed       | passed         | passed      |
| pytorch/models/mit-b0                            | passed      | passed        | passed       | passed         | mismatch    |
| pytorch/models/bert-large-uncased                | passed      | passed        | passed       | passed         | passed      |
| pytorch/models/t5-base                           | passed      | passed        | passed       | passed         | passed      |
| pytorch/models/llama2-7b-hf                      | failed      | notrun        | notrun       | notrun         | notrun      |
| pytorch/models/bge-base-en-v1.5                  | passed      | passed        | passed       | passed         | passed      |

`python ./run.py --torchmlirbuild ../../torch-mlir/build --tolerance 0.001 0.001 --cachedir ./huggingface_cache --ireebuild ../../iree-build  -f onnx -g models --mode onnx --report`

```
Status report for run: test-run using mode:onnx todtype:default backend:llvm-cpu

| tests                                        | model-run   | onnx-import   | torch-mlir   | iree-compile   | inference   |
|:---------------------------------------------|:------------|:--------------|:-------------|:---------------|:------------|
| onnx/models/DenseNet201_vaiq_int8            | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/U-2-Net_vaiq_int8                | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/RegNet_y_8gf_vaiq_int8           | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/DarkNet53_vaiq_int8              | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/pytorch-3dunet_vaiq_int8         | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/RAFT_vaiq_int8                   | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/YoloNetV3_vaiq_int8              | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/yolov8n_vaiq_int8                | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/VideoResNet_vaiq_int8            | passed      | passed        | passed       | failed         | notrun      |
| onnx/models/WideResNet_50_2_vaiq_int8        | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/u-net_brain_mri_vaiq_int8        | passed      | passed        | passed       | passed         | failed      |
| onnx/models/GoogLeNet_vaiq_int8              | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/ShuffleNet_v2_x2_0_vaiq_int8     | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/retinanet_resnet50_fpn_vaiq_int8 | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/DeepLabV3_resnet50_vaiq_int8     | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/RRDB_ESRGAN_vaiq_int8            | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/FCN_vaiq_int8                    | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/llama2-7b-awq                    | failed      | notrun        | notrun       | notrun         | notrun      |
| onnx/models/LRASPP_vaiq_int8                 | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/QuantizedMLP                     | passed      | passed        | passed       | passed         | passed      |
| onnx/models/RDN_pytorch_vaiq_int8            | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/resnet50_vaiq_int8               | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/EfficientNet_v2_s_vaiq_int8      | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/MNASNet_1_3_vaiq_int8            | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/opt-125M-awq                     | passed      | passed        | passed       | failed         | notrun      |
| onnx/models/AlexNet_vaiq_int8                | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/VGG11_bn_vaiq_int8               | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/ResNet152_vaiq_int8              | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/KeypointRCNN_vaiq_int8           | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/CSP-DarkNet_vaiq_int8            | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/SqueezeNet_1_1_vaiq_int8         | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/MobileNetV3_small_vaiq_int8      | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/Inception_v4_vaiq_int8           | passed      | passed        | passed       | failed         | notrun      |
| onnx/models/ConvNeXt_vaiq_int8               | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/VGG19_vaiq_int8                  | passed      | passed        | passed       | passed         | mismatch    |

```

### CODE REVIEW

**Review by PhaneeshB — APPROVED** [review]
LGTM
onnx models would need this too

**Comment by AmosLewis** [comment]
`python ./run.py --torchmlirbuild ../../torch-mlir/build --tolerance 0.001 0.001 --cachedir ./huggingface_cache --ireebuild ../../iree-build  -f onnx -g models --mode onnx --report`

```
Status report for run: test-run using mode:onnx todtype:default backend:llvm-cpu

| tests                                        | model-run   | onnx-import   | torch-mlir   | iree-compile   | inference   |
|:---------------------------------------------|:------------|:--------------|:-------------|:---------------|:------------|
| onnx/models/DenseNet201_vaiq_int8            | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/U-2-Net_vaiq_int8                | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/RegNet_y_8gf_vaiq_int8           | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/DarkNet53_vaiq_int8              | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/pytorch-3dunet_vaiq_int8         | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/RAFT_vaiq_int8                   | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/YoloNetV3_vaiq_int8              | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/yolov8n_vaiq_int8                | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/VideoResNet_vaiq_int8            | passed      | passed        | passed       | failed         | notrun      |
| onnx/models/WideResNet_50_2_vaiq_int8        | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/u-net_brain_mri_vaiq_int8        | passed      | passed        | passed       | passed         | failed      |
| onnx/models/GoogLeNet_vaiq_int8              | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/ShuffleNet_v2_x2_0_vaiq_int8     | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/retinanet_resnet50_fpn_vaiq_int8 | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/DeepLabV3_resnet50_vaiq_int8     | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/RRDB_ESRGAN_vaiq_int8            | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/FCN_vaiq_int8                    | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/llama2-7b-awq                    | failed      | notrun        | notrun       | notrun         | notrun      |
| onnx/models/LRASPP_vaiq_int8                 | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/QuantizedMLP                     | passed      | passed        | passed       | passed         | passed      |
| onnx/models/RDN_pytorch_vaiq_int8            | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/resnet50_vaiq_int8               | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/EfficientNet_v2_s_vaiq_int8      | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/MNASNet_1_3_vaiq_int8            | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/opt-125M-awq                     | passed      | passed        | passed       | failed         | notrun      |
| onnx/models/AlexNet_vaiq_int8                | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/VGG11_bn_vaiq_int8               | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/ResNet152_vaiq_int8              | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/KeypointRCNN_vaiq_int8           | passed      | passed        | failed       | notrun         | notrun      |
| onnx/models/CSP-DarkNet_vaiq_int8            | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/SqueezeNet_1_1_vaiq_int8         | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/MobileNetV3_small_vaiq_int8      | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/Inception_v4_vaiq_int8           | passed      | passed        | passed       | failed         | notrun      |
| onnx/models/ConvNeXt_vaiq_int8               | passed      | passed        | passed       | passed         | mismatch    |
| onnx/models/VGG19_vaiq_int8                  | passed      | passed        | passed       | passed         | mismatch    |

```

**Review by zjgarvey — APPROVED** [review]
Why was the omission of these passes causing numerical problems, I wonder?

**Review by kumardeepakamd — APPROVED** [review]
Looks like good to be landed. Will land it.

**Comment by AmosLewis** [comment]
> Why was the omission of these passes causing numerical problems, I wonder?


Before the change, without `--torchtolinalg`, we won't able to call the torch-mlir's torchtolinag code(`createTorchBackendToLinalgOnTensorsBackendPipeline`), but iree-compiler will call its torch-to-linalg code(`createTorchToIREEPipeline`) https://github.com/iree-org/iree/blob/25fd8a3960cf96f151423b4726bdd8c9e2f75278/compiler/plugins/input/Torch/InputConversion/Passes.cpp#L29, which is adapted from torch-mlir's `createTorchBackendToLinalgOnTensorsBackendPipeline`. The iree function `createTorchToIREEPipeline` should still use the function defined in torchmlir lib/Conversion/TorchToLinalg where recent implementation lowering exist. The `torch-lower-to-backend-contract` from my understanding is mainly bring the decompose of torch ops in. But iree doesnot have the `decompose, cse, canonicalize` when they take a torch dialect as input.  So we need added it after conver-onnx-to-torch. Otherwise, some of the torch ops is not decomposed and not simplyed(aten.reshape->aten.view etc).  

Here is one more example to explain, when we debug onnx ops, we use something like this:
`torch-mlir-opt --convert-torch-onnx-to-torch --torch-decompose-complex-ops --cse --canonicalize --convert-torch-to-linalg reshape.default.onnx.mlir --debug`

**Comment by AmosLewis** [comment]
> Hm, the torch to iree pipeline you linked does, indeed, have decompose complex ops, so I'm still a bit puzzled, but glad the tests are passing.

@zjgarvey 
torch-lower-to-backend-contract is `createLowerToBackendContractPass`
    This pass runs a set of simplifications within that semantic model until
    the backend contract is satisfied, and fails if it cannot be satisfied.
    In particular, the backend contract consists of:
    - Tensors
      - Have been converted to value semantics.
      - Have at least a known rank, though ideally a maximally inferred shape.
      - Have a known dtype.
    - `torch.global_slot`'s have been eliminated from the program.
    - Ops have been decomposed.

**Pull request merged**
