### PR TITLE
Fix setup failures in Huggingface model tests

### PR DESCRIPTION
**Pull request by vinayakdsci**
Updates HF cache locations to respect CACHE_DIR, and fixes a number of setup failures in the HF Model tests.

Also prunes the shard lists to remove some models that Optimum does not have proper ONNX exports for.

### CODE REVIEW

**Review by pdhirajkumarprasad — APPROVED** [review]
approved

**Review by zjgarvey — APPROVED** [review]
Yeah, looks good to me.

**Comment by vinayakdsci** [comment]
@pdhirajkumarprasad @zjgarvey I have updated the shards to remove the models that optimum is unable to export correctly.

Could I have a re-review? Thanks!

**Review by pdhirajkumarprasad — APPROVED** [review]

**Comment by jinchen62** [comment]
I think `optimum` is still needed https://github.com/nod-ai/SHARK-TestSuite/blob/138fe87bd31cb7b88cfd907bfe5bdb8fd7d3348b/alt_e2eshark/onnx_tests/helper_classes.py#L35

**Pull request merged**
