### PR TITLE
removing model which are not valid and duplicates

### PR DESCRIPTION
**Pull request by pdhirajkumarprasad**
removing models from list which are not valid based on https://github.com/nod-ai/SHARK-ModelDev/issues/812 and remove duplicates using tool introduced here: https://github.com/nod-ai/SHARK-TestSuite/pull/376

### CODE REVIEW

**Comment by saienduri** [comment]
LGTM, let's wait for @zjgarvey before landing

**Review by zjgarvey — COMMENTED** [review]
I'd like to retain the original shard lists somewhere. I'm not sure if Kumar or others want to still have numbers reported based on the full list with redundant tests.

 Do we also need to redistribute across shards?

**Comment by pdhirajkumarprasad** [comment]
> I'd like to retain the original shard lists somewhere. I'm not sure if Kumar or others want to still have numbers reported based on the full list with redundant tests.

--I can keep the original list with extension _old but our run should be with the unique model list and it's fine if that lead to lesser no. of model but that will be unique list  

> Do we also need to redistribute across shards?

--Yes, I can do that

**Comment by pdhirajkumarprasad** [comment]
closing this pull request as the way DUP model was found is not correct and it will reduce the coverage of ops. Once we have correct list, will create the pull request

**Pull request closed without merging**
