### PR TITLE
Model Tests with working model.py

### PR DESCRIPTION
**Pull request by afalkenberg1**
RAFT_vaiq_int8
RDN_pytorch_vaiq_int8
pytorch-3dunet_vaiq_int8
(no change in MobileNetV3_small_vaiq_int8 needed)

Generated issues #598 #599

This commit is to provide correctly adapted model.py files to allow the test cases to run. 
model.onnx need to be downloaded still.

### CODE REVIEW

**Comment by kumardeepakamd** [comment]
@PhaneeshB would be good for you to review this to make sure it is aligned with your xhanges to enable onnx model download and run from azure storage

**Comment by kumardeepakamd** [comment]
These changes seem independent of run.py changes, so should be good to merge

**Review by PhaneeshB — CHANGES_REQUESTED** [review]
Changes for RAFT, RDN and 3dunet seem good to merge
not seeing changes for MobileNetV3_small, perhaps just missed that file?
Once you can add that in too we'll be good to merge :) (we can skip that too but don't want already completed work go unused)

**Comment by afalkenberg1** [comment]
> Changes for RAFT, RDN and 3dunet seem good to merge not seeing changes for MobileNetV3_small, perhaps just missed that file? Once you can add that in too we'll be good to merge :) (we can skip that too but don't want already completed work go unused)

**Review by PhaneeshB — APPROVED** [review]
LGTM!

**Pull request merged**
